# Generated by Django 3.0.5 on 2020-04-21 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('slug', models.SlugField(blank=True, max_length=31, null=True)),
                ('description', models.TextField(blank=True)),
                ('youtube_page', models.URLField(blank=True, max_length=127)),
                ('website', models.URLField(blank=True, max_length=127)),
                ('apple_page', models.URLField(blank=True, max_length=127)),
                ('spotify_page', models.URLField(blank=True, max_length=127)),
                ('categories', models.ManyToManyField(to='categories.Category')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personalities', models.ManyToManyField(to='personalities.Personality')),
            ],
            options={
                'verbose_name': 'podcast',
                'verbose_name_plural': 'podcasts',
            },
        ),
    ]
