# Generated by Django 3.0.5 on 2020-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('personalities', '0001_initial'),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='personalities',
        ),
        migrations.AddField(
            model_name='podcast',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='personalities.Personality'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
