# Generated by Django 3.0.5 on 2020-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalities', '0001_initial'),
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='personalities',
            field=models.ManyToManyField(blank=True, to='personalities.Personality'),
        ),
    ]
