# Generated by Django 3.0.5 on 2020-05-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20200430_1625'),
        ('episodes', '0002_episode_personalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
            preserve_default=False,
        ),
    ]
