# Generated by Django 3.0.5 on 2020-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=31)),
                ('lastname', models.CharField(max_length=31)),
                ('displayname', models.CharField(max_length=31)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Personality',
                'verbose_name_plural': 'Personalities',
            },
        ),
    ]
